<style>
    html {
        height: 100%;
        width: 100%;
        margin: 0px !important;
    }
    body {
        width: 100%;
        height: 100%;
        display: table;
        margin: 0px;
        background: url('img/min/background.jpg') no-repeat center center fixed !important;
        background-size: 100% 100% !important;
        background-color: black;
    }
    a {
        text-decoration: none;
        color: inherit;
    }
    #center-content {
        display: table;
        margin: 20px auto 0px auto;
        text-align: center;
    }

    #title {
        position: relative;
        margin-bottom: 20px;
        font-family: 'open sans';
        width: 100%;
        text-align: center;
        font-size: 3.5em;
        text-transform: uppercase;
        font-weight: 300;
        color: white;
        line-height: 1.2;
        text-shadow: 0 0 0.07em white;
        padding-bottom: 2px;
    }

    #title::after{
        content: "";
        position: absolute;
        bottom: 2px;
        left: 0;
        height: 1px;
        width: 100%;
        background: white;
        background: -webkit-linear-gradient(left, transparent 0%,#fff 50%,transparent 100%);
        background: -moz-linear-gradient(left, transparent 0%,#fff 50%,transparent 100%);
        background: -o-linear-gradient(left, transparent 0%,#fff 50%,transparent 100%);
        background: linear-gradient(left, transparent 0%,#fff 50%,transparent 100%);
    }

    #title-description {
        height: 100%;
        margin-bottom: 20px;
        font-family: 'open sans';
        width: 100%;
        text-align: center;
        font-size: 3.5em;
        text-transform: uppercase;
        font-weight: bold;
        color: white;
        line-height: 1.2;
        text-shadow: 0 0 0.07em white;

    }

    #social {
        magin-top: 5px;
        text-align: center;
        font-size: 32px;
        color: rgba(255,255,255, 1);
        opacity: 0.6;
    }

    #headshot {
        width: 30%;
        height: 30%;
    }

    #nav-bar {
        width: 50%;
        margin: 0px auto;
        padding: 20px 20px 0px 20px;
        border-radius: 10px 10px 0px 0px;
        background-color: #19181a;
        display:table;
        font-family: 'open sans';
        text-align: center;
        font-size: 1.5em;
        text-transform: uppercase;
        font-weight: 300;
        color: white;
        line-height: 1.2;
        text-shadow: 0 0 0.04em white;
        margin: 0px auto;
        box-shadow: 0 2px 10px 0 rgba(0,0,0,.6);
    }

    #nav-wrapper {
        display: table;
        margin: 0px auto;
    }
    .nav-item {
        opacity: 0.8;
        float: left;
        padding: 10px 15px;
        border-bottom: solid 1px #313032;
    }


</style>