<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<link href='//cdn.jsdelivr.net/devicons/1.8.0/css/devicons.min.css' rel='stylesheet'>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-route.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="components/ace/ace.js"></script>
<script src="js/app.js"></script>

<link href="css/main.css" rel='stylesheet' type='text/css'>
<link href="css/about.css" rel='stylesheet' type='text/css'>
<link href="css/nav.css" rel='stylesheet' type='text/css'>
<link href="css/experience.css" rel='stylesheet' type='text/css'>
<link href="css/skills.css" rel='stylesheet' type='text/css'>