<meta charset="UTF-8">
<title>Valenciana</title>
<meta name="author" content="Dominic Valenciana">
<meta name="description" content="The person website of Dominic Valenciana. This website displays works of Dominic Valencian as a developer and designer.">
<meta name="keywords" content="Dominic,Valenciana,kiricon,web,design,html,css,html5,development,developer">
<meta name="viewport" content="width=device-width, user-scalable=no">
<link rel="shortcut icon" href="img/favicon.ico" />
<base href="/">