<div id="nav-bar" ng-class="{navshow:!tab.isSet('/')}" style="border-radius: 10px !important; padding: 0px !important; margin-bottom: 20px;">
    <div id="nav-wrapper">
        <div class="nav-item" ng-class="{active:tab.isSet('/skills')}"><a href="skills">Skills</a></div>
        <div class="nav-item" ng-class="{active:tab.isSet('/experience')}"><a href="experience">Experience</a></div>
        <div class="nav-item" ng-class="{active:tab.isSet('/about')}"><a href="about">About</a></div>
    </div>
</div>