<!DOCTYPE html>
<html ng-app="app">
<head lang="en">
    {% include "partials/header.phtml" %}
    {% include "partials/experiencecss.phtml" %}
</head>
<body ng-controller="TabController as tab">
  <div id="overlay"></div>
<div id="center-content">
    <div id="title"><a href="welcome">Dominic Valenciana</a></div>
    <a href="welcome"><img id="headshot" onload="this.style.opacity='1';" src="img/min/profile.jpg" style="border-radius:50%; box-shadow: 0 6px 20px 0 rgba(0,0,0,.19);"></a>
    {% include "partials/social.phtml" %}
</div>
{% include "partials/navbar.phtml" %}

<div ng-view></div>
{% include "partials/footer.phtml" %}
</body>
</html>
